/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Hd55AmbulanceWlList {
    }
}
declare global {
    interface HTMLHd55AmbulanceWlListElement extends Components.Hd55AmbulanceWlList, HTMLStencilElement {
    }
    var HTMLHd55AmbulanceWlListElement: {
        prototype: HTMLHd55AmbulanceWlListElement;
        new (): HTMLHd55AmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "hd55-ambulance-wl-list": HTMLHd55AmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface Hd55AmbulanceWlList {
    }
    interface IntrinsicElements {
        "hd55-ambulance-wl-list": Hd55AmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "hd55-ambulance-wl-list": LocalJSX.IntrinsicElements["hd55-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLHd55AmbulanceWlListElement>;
        }
    }
}
